// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greete_SayHello_FullMethodName    = "/Greete/SayHello"
	Greete_HelloStream_FullMethodName = "/Greete/HelloStream"
)

// GreeteClient is the client API for Greete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeteClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	HelloStream(ctx context.Context, opts ...grpc.CallOption) (Greete_HelloStreamClient, error)
}

type greeteClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeteClient(cc grpc.ClientConnInterface) GreeteClient {
	return &greeteClient{cc}
}

func (c *greeteClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Greete_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeteClient) HelloStream(ctx context.Context, opts ...grpc.CallOption) (Greete_HelloStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greete_ServiceDesc.Streams[0], Greete_HelloStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeteHelloStreamClient{stream}
	return x, nil
}

type Greete_HelloStreamClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greeteHelloStreamClient struct {
	grpc.ClientStream
}

func (x *greeteHelloStreamClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeteHelloStreamClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeteServer is the server API for Greete service.
// All implementations must embed UnimplementedGreeteServer
// for forward compatibility
type GreeteServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	HelloStream(Greete_HelloStreamServer) error
	mustEmbedUnimplementedGreeteServer()
}

// UnimplementedGreeteServer must be embedded to have forward compatible implementations.
type UnimplementedGreeteServer struct {
}

func (UnimplementedGreeteServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeteServer) HelloStream(Greete_HelloStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HelloStream not implemented")
}
func (UnimplementedGreeteServer) mustEmbedUnimplementedGreeteServer() {}

// UnsafeGreeteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeteServer will
// result in compilation errors.
type UnsafeGreeteServer interface {
	mustEmbedUnimplementedGreeteServer()
}

func RegisterGreeteServer(s grpc.ServiceRegistrar, srv GreeteServer) {
	s.RegisterService(&Greete_ServiceDesc, srv)
}

func _Greete_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeteServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greete_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeteServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greete_HelloStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeteServer).HelloStream(&greeteHelloStreamServer{stream})
}

type Greete_HelloStreamServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeteHelloStreamServer struct {
	grpc.ServerStream
}

func (x *greeteHelloStreamServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeteHelloStreamServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greete_ServiceDesc is the grpc.ServiceDesc for Greete service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greete_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greete",
	HandlerType: (*GreeteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greete_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloStream",
			Handler:       _Greete_HelloStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hello.proto",
}
