// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RepeatData struct {
	Data                 []*RepeatData_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RepeatData) Reset()         { *m = RepeatData{} }
func (m *RepeatData) String() string { return proto.CompactTextString(m) }
func (*RepeatData) ProtoMessage()    {}
func (*RepeatData) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2}
}

func (m *RepeatData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatData.Unmarshal(m, b)
}
func (m *RepeatData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatData.Marshal(b, m, deterministic)
}
func (m *RepeatData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatData.Merge(m, src)
}
func (m *RepeatData) XXX_Size() int {
	return xxx_messageInfo_RepeatData.Size(m)
}
func (m *RepeatData) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatData.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatData proto.InternalMessageInfo

func (m *RepeatData) GetData() []*RepeatData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type RepeatData_Data struct {
	// Types that are valid to be assigned to Data:
	//	*RepeatData_Data_Req
	//	*RepeatData_Data_Rsp
	Data                 isRepeatData_Data_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RepeatData_Data) Reset()         { *m = RepeatData_Data{} }
func (m *RepeatData_Data) String() string { return proto.CompactTextString(m) }
func (*RepeatData_Data) ProtoMessage()    {}
func (*RepeatData_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{2, 0}
}

func (m *RepeatData_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatData_Data.Unmarshal(m, b)
}
func (m *RepeatData_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatData_Data.Marshal(b, m, deterministic)
}
func (m *RepeatData_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatData_Data.Merge(m, src)
}
func (m *RepeatData_Data) XXX_Size() int {
	return xxx_messageInfo_RepeatData_Data.Size(m)
}
func (m *RepeatData_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatData_Data.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatData_Data proto.InternalMessageInfo

type isRepeatData_Data_Data interface {
	isRepeatData_Data_Data()
}

type RepeatData_Data_Req struct {
	Req *HelloRequest `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type RepeatData_Data_Rsp struct {
	Rsp *HelloResponse `protobuf:"bytes,2,opt,name=rsp,proto3,oneof"`
}

func (*RepeatData_Data_Req) isRepeatData_Data_Data() {}

func (*RepeatData_Data_Rsp) isRepeatData_Data_Data() {}

func (m *RepeatData_Data) GetData() isRepeatData_Data_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RepeatData_Data) GetReq() *HelloRequest {
	if x, ok := m.GetData().(*RepeatData_Data_Req); ok {
		return x.Req
	}
	return nil
}

func (m *RepeatData_Data) GetRsp() *HelloResponse {
	if x, ok := m.GetData().(*RepeatData_Data_Rsp); ok {
		return x.Rsp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RepeatData_Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RepeatData_Data_Req)(nil),
		(*RepeatData_Data_Rsp)(nil),
	}
}

type Common struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Common) Reset()         { *m = Common{} }
func (m *Common) String() string { return proto.CompactTextString(m) }
func (*Common) ProtoMessage()    {}
func (*Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{3}
}

func (m *Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common.Unmarshal(m, b)
}
func (m *Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common.Marshal(b, m, deterministic)
}
func (m *Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common.Merge(m, src)
}
func (m *Common) XXX_Size() int {
	return xxx_messageInfo_Common.Size(m)
}
func (m *Common) XXX_DiscardUnknown() {
	xxx_messageInfo_Common.DiscardUnknown(m)
}

var xxx_messageInfo_Common proto.InternalMessageInfo

func (m *Common) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Common) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type BatchRequest struct {
	Requests             []*Common `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BatchRequest) Reset()         { *m = BatchRequest{} }
func (m *BatchRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()    {}
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61ef911816e0a8ce, []int{4}
}

func (m *BatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequest.Unmarshal(m, b)
}
func (m *BatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequest.Marshal(b, m, deterministic)
}
func (m *BatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequest.Merge(m, src)
}
func (m *BatchRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRequest.Size(m)
}
func (m *BatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequest proto.InternalMessageInfo

func (m *BatchRequest) GetRequests() []*Common {
	if m != nil {
		return m.Requests
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*RepeatData)(nil), "RepeatData")
	proto.RegisterType((*RepeatData_Data)(nil), "RepeatData.Data")
	proto.RegisterType((*Common)(nil), "Common")
	proto.RegisterType((*BatchRequest)(nil), "BatchRequest")
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_61ef911816e0a8ce) }

var fileDescriptor_61ef911816e0a8ce = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0xeb, 0x7f, 0xf2, 0x4f, 0xda, 0x4b, 0x8a, 0x90, 0xa7, 0xa8, 0x53, 0x31, 0x0c, 0xe9,
	0x62, 0xaa, 0xf4, 0x0d, 0x02, 0x12, 0x9d, 0x5d, 0xb1, 0xb0, 0x99, 0xf6, 0xd4, 0x0e, 0x4d, 0x9c,
	0xda, 0x66, 0xe0, 0x11, 0x78, 0x6b, 0xe4, 0x4b, 0x03, 0x94, 0x85, 0x25, 0xb9, 0xbb, 0xef, 0xd3,
	0xe7, 0xdf, 0xd9, 0x90, 0x1d, 0xf0, 0x78, 0x34, 0xb2, 0xb3, 0xc6, 0x1b, 0x21, 0x20, 0x5f, 0x87,
	0x56, 0xe1, 0xe9, 0x0d, 0x9d, 0xe7, 0x1c, 0xe2, 0x56, 0x37, 0x58, 0xb0, 0x39, 0x2b, 0x27, 0x8a,
	0x6a, 0xb1, 0x80, 0xe9, 0xd9, 0xe3, 0x3a, 0xd3, 0x3a, 0xe4, 0x05, 0xa4, 0x0d, 0x3a, 0xa7, 0xf7,
	0x83, 0x6f, 0x68, 0xc5, 0x07, 0x03, 0x50, 0xd8, 0xa1, 0xf6, 0x8f, 0xda, 0x6b, 0x7e, 0x07, 0xf1,
	0x4e, 0x7b, 0x5d, 0xb0, 0x79, 0x54, 0x66, 0xd5, 0xb5, 0xfc, 0x96, 0x64, 0xf8, 0x28, 0x52, 0x67,
	0xcf, 0x10, 0x93, 0xfb, 0x06, 0x22, 0x8b, 0x27, 0x8a, 0xcc, 0xaa, 0xa9, 0xfc, 0xc9, 0xb5, 0x1e,
	0xa9, 0xa0, 0x71, 0x01, 0x91, 0x75, 0x5d, 0xf1, 0x8f, 0x2c, 0x57, 0xf2, 0x02, 0x8b, 0x3c, 0xae,
	0xab, 0x93, 0xfe, 0x50, 0xb1, 0x84, 0xe4, 0xc1, 0x34, 0x8d, 0x69, 0xc3, 0x52, 0x5b, 0xb3, 0xeb,
	0x61, 0xff, 0x2b, 0xaa, 0xc3, 0x8c, 0xd0, 0x42, 0x54, 0xde, 0x83, 0x88, 0x15, 0xe4, 0xb5, 0xf6,
	0xdb, 0xc3, 0x70, 0x19, 0xb7, 0x30, 0xb6, 0x7d, 0xe9, 0xce, 0x2b, 0xa4, 0xb2, 0x8f, 0x54, 0x5f,
	0x42, 0xb5, 0x87, 0xe4, 0xc9, 0x22, 0x7a, 0xe4, 0x0b, 0x18, 0x6f, 0xf4, 0x3b, 0x31, 0xf1, 0x4b,
	0xfc, 0xd9, 0x2f, 0x54, 0x5e, 0x41, 0x46, 0x83, 0x8d, 0xb7, 0xa8, 0x9b, 0x3f, 0xdc, 0x62, 0x54,
	0xb2, 0x25, 0xab, 0x27, 0x2f, 0xa9, 0xbc, 0xa7, 0x57, 0x7b, 0x4d, 0xe8, 0xb7, 0xfa, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xcf, 0x35, 0xe6, 0xe3, 0xcb, 0x01, 0x00, 0x00,
}
