// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldType struct {
	F1                   int32            `protobuf:"varint,1,opt,name=F1,proto3" json:"F1,omitempty"`
	F2                   uint32           `protobuf:"fixed32,2,opt,name=F2,proto3" json:"F2,omitempty"`
	F3                   string           `protobuf:"bytes,3,opt,name=F3,proto3" json:"F3,omitempty"`
	F4                   []string         `protobuf:"bytes,4,rep,name=F4,proto3" json:"F4,omitempty"`
	F5                   map[string]int32 `protobuf:"bytes,5,rep,name=F5,proto3" json:"F5,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	F6                   uint32           `protobuf:"varint,6,opt,name=F6,proto3" json:"F6,omitempty"`
	F7                   int32            `protobuf:"zigzag32,7,opt,name=F7,proto3" json:"F7,omitempty"`
	F999                 bool             `protobuf:"varint,999999,opt,name=F999,proto3" json:"F999,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FieldType) Reset()         { *m = FieldType{} }
func (m *FieldType) String() string { return proto.CompactTextString(m) }
func (*FieldType) ProtoMessage()    {}
func (*FieldType) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *FieldType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldType.Unmarshal(m, b)
}
func (m *FieldType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldType.Marshal(b, m, deterministic)
}
func (m *FieldType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldType.Merge(m, src)
}
func (m *FieldType) XXX_Size() int {
	return xxx_messageInfo_FieldType.Size(m)
}
func (m *FieldType) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldType.DiscardUnknown(m)
}

var xxx_messageInfo_FieldType proto.InternalMessageInfo

func (m *FieldType) GetF1() int32 {
	if m != nil {
		return m.F1
	}
	return 0
}

func (m *FieldType) GetF2() uint32 {
	if m != nil {
		return m.F2
	}
	return 0
}

func (m *FieldType) GetF3() string {
	if m != nil {
		return m.F3
	}
	return ""
}

func (m *FieldType) GetF4() []string {
	if m != nil {
		return m.F4
	}
	return nil
}

func (m *FieldType) GetF5() map[string]int32 {
	if m != nil {
		return m.F5
	}
	return nil
}

func (m *FieldType) GetF6() uint32 {
	if m != nil {
		return m.F6
	}
	return 0
}

func (m *FieldType) GetF7() int32 {
	if m != nil {
		return m.F7
	}
	return 0
}

func (m *FieldType) GetF999() bool {
	if m != nil {
		return m.F999
	}
	return false
}

func init() {
	proto.RegisterType((*FieldType)(nil), "FieldType")
	proto.RegisterMapType((map[string]int32)(nil), "FieldType.F5Entry")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0x76, 0xd2, 0x34, 0x66, 0x45, 0xd1, 0xa5, 0x87, 0xc5, 0xd3, 0x90, 0xd3, 0x5e,
	0x4c, 0x68, 0xd2, 0xb4, 0x46, 0xf0, 0x22, 0x38, 0x0f, 0x30, 0x78, 0xf2, 0x56, 0xeb, 0x12, 0xc4,
	0xb6, 0x09, 0xb1, 0x8a, 0x7b, 0xf7, 0xbd, 0x7c, 0x11, 0x1f, 0x46, 0x32, 0x8a, 0x97, 0xdd, 0xf9,
	0x0e, 0xf3, 0xf3, 0x33, 0x3a, 0xdd, 0xbd, 0xb6, 0x79, 0x3f, 0x74, 0x87, 0x2e, 0xfb, 0x56, 0x3a,
	0xa5, 0x67, 0xbf, 0x7d, 0xba, 0x0f, 0xbd, 0x37, 0xa7, 0x1a, 0x68, 0x6e, 0x15, 0x2a, 0x17, 0x33,
	0xd0, 0x5c, 0x5c, 0x5a, 0x40, 0xe5, 0x12, 0x06, 0x2a, 0xc5, 0x95, 0x8d, 0x50, 0xb9, 0x94, 0x81,
	0x2a, 0xf1, 0xc2, 0x4e, 0x30, 0x12, 0x2f, 0x4c, 0xa6, 0x81, 0x6a, 0x1b, 0x63, 0xe4, 0x8e, 0x4b,
	0x93, 0xff, 0xe7, 0xe6, 0x54, 0xdf, 0xed, 0x0f, 0x43, 0x60, 0xa0, 0x5a, 0x76, 0x96, 0x76, 0x8a,
	0xca, 0x9d, 0x30, 0xd0, 0x52, 0xbc, 0xb2, 0x09, 0x2a, 0x77, 0xce, 0x40, 0x2b, 0x33, 0xd3, 0x13,
	0x6a, 0x9a, 0xc6, 0x7e, 0x7d, 0xde, 0xa0, 0x72, 0x47, 0x2c, 0xba, 0xa8, 0x75, 0xf2, 0x17, 0x62,
	0xce, 0x74, 0xf4, 0xe2, 0x83, 0xb4, 0x4c, 0x79, 0x1c, 0xcd, 0x4c, 0xc7, 0xef, 0xeb, 0xed, 0x9b,
	0x97, 0xa6, 0x31, 0xff, 0xe2, 0x1a, 0xae, 0xd4, 0x6d, 0xf6, 0x80, 0xed, 0x7a, 0x1f, 0x42, 0xc8,
	0x37, 0xdd, 0xae, 0x68, 0xbb, 0x4b, 0xff, 0xd1, 0x17, 0x43, 0xbf, 0x29, 0xda, 0xf1, 0x91, 0x13,
	0x3c, 0x4e, 0xe5, 0xab, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x77, 0xab, 0x7b, 0x97, 0x16, 0x01,
	0x00, 0x00,
}
