version: '3'
services:
  nats1:
    image: 'nats:2.8.4-linux'
    ports:
    - "4225:4222"
    - "8225:8222"
    networks:
    - 'nats'
    command: [ "--config", "/data/nats1.conf"]
    volumes:
    - conf-data:/data

  nats2:
    image: 'nats:2.8.4-linux'
    ports:
    - "4223:4222"
    - "8223:8222"
    networks:
    - 'nats'
    command: [ "--config", "/data/nats1.conf"]
    volumes:
    - conf-data:/data
    depends_on:
    - 'nats1'

  nats3:
    image: 'nats:2.8.4-linux'
    ports:
    - "4224:4222"
    - "8224:8222"
    networks:
    - 'nats'
    command: [ "--config", "/data/nats1.conf"]
    depends_on:
    - 'nats1'
    volumes:
    - conf-data:/data

networks:
  nats:
    driver: 'bridge'

volumes:
  conf-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /Users/Gann/Project/code/golang/go-exp/demo/nats/cluster