// Code generated by "stringer -type innerErrCode -output const_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNo-0]
	_ = x[ErrWaitTimeout-1]
	_ = x[ErrAddTimeout-2]
	_ = x[ErrInner-3]
	_ = x[ErrTaskType-4]
	_ = x[ErrChanFull-5]
}

const _innerErrCode_name = "ErrNoErrWaitTimeoutErrAddTimeoutErrInnerErrTaskTypeErrChanFull"

var _innerErrCode_index = [...]uint8{0, 5, 19, 32, 40, 51, 62}

func (i innerErrCode) String() string {
	if i >= innerErrCode(len(_innerErrCode_index)-1) {
		return "innerErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _innerErrCode_name[_innerErrCode_index[i]:_innerErrCode_index[i+1]]
}
