// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: player.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acid          string                 `protobuf:"bytes,1,opt,name=Acid,proto3" json:"Acid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoReq) Reset() {
	*x = GetPlayerInfoReq{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoReq) ProtoMessage() {}

func (x *GetPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerInfoReq) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

type GetPlayerInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Acid          string                 `protobuf:"bytes,4,opt,name=Acid,proto3" json:"Acid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoRsp) Reset() {
	*x = GetPlayerInfoRsp{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRsp) ProtoMessage() {}

func (x *GetPlayerInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRsp.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRsp) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPlayerInfoRsp) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

type NotifyInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Acid          string                 `protobuf:"bytes,2,opt,name=Acid,proto3" json:"Acid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyInfoReq) Reset() {
	*x = NotifyInfoReq{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInfoReq) ProtoMessage() {}

func (x *NotifyInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInfoReq.ProtoReflect.Descriptor instead.
func (*NotifyInfoReq) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyInfoReq) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

type GetNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acid          string                 `protobuf:"bytes,1,opt,name=Acid,proto3" json:"Acid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNameReq) Reset() {
	*x = GetNameReq{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameReq) ProtoMessage() {}

func (x *GetNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameReq.ProtoReflect.Descriptor instead.
func (*GetNameReq) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetNameReq) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

type GetNameRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNameRsp) Reset() {
	*x = GetNameRsp{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNameRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameRsp) ProtoMessage() {}

func (x *GetNameRsp) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameRsp.ProtoReflect.Descriptor instead.
func (*GetNameRsp) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *GetNameRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NotifyAddAgeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acid          string                 `protobuf:"bytes,1,opt,name=Acid,proto3" json:"Acid,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyAddAgeReq) Reset() {
	*x = NotifyAddAgeReq{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyAddAgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyAddAgeReq) ProtoMessage() {}

func (x *NotifyAddAgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyAddAgeReq.ProtoReflect.Descriptor instead.
func (*NotifyAddAgeReq) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyAddAgeReq) GetAcid() string {
	if x != nil {
		return x.Acid
	}
	return ""
}

func (x *NotifyAddAgeReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\rplayer_module\x1a\fcommon.proto\"&\n" +
	"\x10GetPlayerInfoReq\x12\x12\n" +
	"\x04Acid\x18\x01 \x01(\tR\x04Acid\":\n" +
	"\x10GetPlayerInfoRsp\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Acid\x18\x04 \x01(\tR\x04Acid\"7\n" +
	"\rNotifyInfoReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Acid\x18\x02 \x01(\tR\x04Acid\" \n" +
	"\n" +
	"GetNameReq\x12\x12\n" +
	"\x04Acid\x18\x01 \x01(\tR\x04Acid\" \n" +
	"\n" +
	"GetNameRsp\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"7\n" +
	"\x0fNotifyAddAgeReq\x12\x12\n" +
	"\x04Acid\x18\x01 \x01(\tR\x04Acid\x12\x10\n" +
	"\x03Age\x18\x02 \x01(\x05R\x03Age2\x9c\x02\n" +
	"\fPlayerModule\x129\n" +
	"\n" +
	"NotifyInfo\x12\x1c.player_module.NotifyInfoReq\x1a\r.common.Empty\x12Q\n" +
	"\rGetPlayerInfo\x12\x1f.player_module.GetPlayerInfoReq\x1a\x1f.player_module.GetPlayerInfoRsp\x12?\n" +
	"\aGetName\x12\x19.player_module.GetNameReq\x1a\x19.player_module.GetNameRsp\x12=\n" +
	"\fNotifyAddAge\x12\x1e.player_module.NotifyAddAgeReq\x1a\r.common.EmptyB\x1fZ\x1dprotoc-gen-go-handle/protogenb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_player_proto_goTypes = []any{
	(*GetPlayerInfoReq)(nil), // 0: player_module.GetPlayerInfoReq
	(*GetPlayerInfoRsp)(nil), // 1: player_module.GetPlayerInfoRsp
	(*NotifyInfoReq)(nil),    // 2: player_module.NotifyInfoReq
	(*GetNameReq)(nil),       // 3: player_module.GetNameReq
	(*GetNameRsp)(nil),       // 4: player_module.GetNameRsp
	(*NotifyAddAgeReq)(nil),  // 5: player_module.NotifyAddAgeReq
	(*Empty)(nil),            // 6: common.Empty
}
var file_player_proto_depIdxs = []int32{
	2, // 0: player_module.PlayerModule.NotifyInfo:input_type -> player_module.NotifyInfoReq
	0, // 1: player_module.PlayerModule.GetPlayerInfo:input_type -> player_module.GetPlayerInfoReq
	3, // 2: player_module.PlayerModule.GetName:input_type -> player_module.GetNameReq
	5, // 3: player_module.PlayerModule.NotifyAddAge:input_type -> player_module.NotifyAddAgeReq
	6, // 4: player_module.PlayerModule.NotifyInfo:output_type -> common.Empty
	1, // 5: player_module.PlayerModule.GetPlayerInfo:output_type -> player_module.GetPlayerInfoRsp
	4, // 6: player_module.PlayerModule.GetName:output_type -> player_module.GetNameRsp
	6, // 7: player_module.PlayerModule.NotifyAddAge:output_type -> common.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
