// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: room_mgr.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	mi := &file_room_mgr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CreateRoomRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRsp) Reset() {
	*x = CreateRoomRsp{}
	mi := &file_room_mgr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRsp) ProtoMessage() {}

func (x *CreateRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRsp.ProtoReflect.Descriptor instead.
func (*CreateRoomRsp) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomRsp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	mi := &file_room_mgr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinRoomRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Test          string                 `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRsp) Reset() {
	*x = JoinRoomRsp{}
	mi := &file_room_mgr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRsp) ProtoMessage() {}

func (x *JoinRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRsp.ProtoReflect.Descriptor instead.
func (*JoinRoomRsp) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomRsp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRsp) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

type LeaveRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomReq) Reset() {
	*x = LeaveRoomReq{}
	mi := &file_room_mgr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReq) ProtoMessage() {}

func (x *LeaveRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReq.ProtoReflect.Descriptor instead.
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LeaveRoomRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRsp) Reset() {
	*x = LeaveRoomRsp{}
	mi := &file_room_mgr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRsp) ProtoMessage() {}

func (x *LeaveRoomRsp) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRsp.ProtoReflect.Descriptor instead.
func (*LeaveRoomRsp) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRoomRsp) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type NotifyBattleStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyBattleStartReq) Reset() {
	*x = NotifyBattleStartReq{}
	mi := &file_room_mgr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyBattleStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBattleStartReq) ProtoMessage() {}

func (x *NotifyBattleStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_mgr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBattleStartReq.ProtoReflect.Descriptor instead.
func (*NotifyBattleStartReq) Descriptor() ([]byte, []int) {
	return file_room_mgr_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyBattleStartReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotifyBattleStartReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

var File_room_mgr_proto protoreflect.FileDescriptor

const file_room_mgr_proto_rawDesc = "" +
	"\n" +
	"\x0eroom_mgr.proto\x12\abattlex\x1a\fcommon.proto\"C\n" +
	"\rCreateRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\"'\n" +
	"\rCreateRoomRsp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"A\n" +
	"\vJoinRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\"9\n" +
	"\vJoinRoomRsp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04test\x18\x02 \x01(\tR\x04test\"B\n" +
	"\fLeaveRoomReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId\"&\n" +
	"\fLeaveRoomRsp\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\"J\n" +
	"\x14NotifyBattleStartReq\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\tR\bplayerId2\xfd\x01\n" +
	"\aRoomMgr\x12<\n" +
	"\n" +
	"CreateRoom\x12\x16.battlex.CreateRoomReq\x1a\x16.battlex.CreateRoomRsp\x126\n" +
	"\bJoinRoom\x12\x14.battlex.JoinRoomReq\x1a\x14.battlex.JoinRoomRsp\x129\n" +
	"\tLeaveRoom\x12\x15.battlex.LeaveRoomReq\x1a\x15.battlex.LeaveRoomRsp\x12A\n" +
	"\x11NotifyBattleStart\x12\x1d.battlex.NotifyBattleStartReq\x1a\r.common.EmptyB\x1fZ\x1dprotoc-gen-go-handle/protogenb\x06proto3"

var (
	file_room_mgr_proto_rawDescOnce sync.Once
	file_room_mgr_proto_rawDescData []byte
)

func file_room_mgr_proto_rawDescGZIP() []byte {
	file_room_mgr_proto_rawDescOnce.Do(func() {
		file_room_mgr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_mgr_proto_rawDesc), len(file_room_mgr_proto_rawDesc)))
	})
	return file_room_mgr_proto_rawDescData
}

var file_room_mgr_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_room_mgr_proto_goTypes = []any{
	(*CreateRoomReq)(nil),        // 0: battlex.CreateRoomReq
	(*CreateRoomRsp)(nil),        // 1: battlex.CreateRoomRsp
	(*JoinRoomReq)(nil),          // 2: battlex.JoinRoomReq
	(*JoinRoomRsp)(nil),          // 3: battlex.JoinRoomRsp
	(*LeaveRoomReq)(nil),         // 4: battlex.LeaveRoomReq
	(*LeaveRoomRsp)(nil),         // 5: battlex.LeaveRoomRsp
	(*NotifyBattleStartReq)(nil), // 6: battlex.NotifyBattleStartReq
	(*Empty)(nil),                // 7: common.Empty
}
var file_room_mgr_proto_depIdxs = []int32{
	0, // 0: battlex.RoomMgr.CreateRoom:input_type -> battlex.CreateRoomReq
	2, // 1: battlex.RoomMgr.JoinRoom:input_type -> battlex.JoinRoomReq
	4, // 2: battlex.RoomMgr.LeaveRoom:input_type -> battlex.LeaveRoomReq
	6, // 3: battlex.RoomMgr.NotifyBattleStart:input_type -> battlex.NotifyBattleStartReq
	1, // 4: battlex.RoomMgr.CreateRoom:output_type -> battlex.CreateRoomRsp
	3, // 5: battlex.RoomMgr.JoinRoom:output_type -> battlex.JoinRoomRsp
	5, // 6: battlex.RoomMgr.LeaveRoom:output_type -> battlex.LeaveRoomRsp
	7, // 7: battlex.RoomMgr.NotifyBattleStart:output_type -> common.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_mgr_proto_init() }
func file_room_mgr_proto_init() {
	if File_room_mgr_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_mgr_proto_rawDesc), len(file_room_mgr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_mgr_proto_goTypes,
		DependencyIndexes: file_room_mgr_proto_depIdxs,
		MessageInfos:      file_room_mgr_proto_msgTypes,
	}.Build()
	File_room_mgr_proto = out.File
	file_room_mgr_proto_goTypes = nil
	file_room_mgr_proto_depIdxs = nil
}
