version: "3"
services:
  nats1:
    image: nats:2.10.12-linux
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ 
        "--config", "/conf/nats.conf", 
        "--server_name", "nats1",
      ]
    networks:
      - nats
    volumes:
      - ./nats.conf:/conf/nats.conf
      - ./data/nats1:/data
  nats2:
    image: nats:2.10.12-linux
    ports:
      - "4223:4222"
      - "8223:8222"
    command: [ 
        "--config", "/conf/nats.conf", 
        "--server_name", "nats2",
      ]
    depends_on:
      - 'nats1'
    networks:
      - nats
    volumes:
      - ./nats.conf:/conf/nats.conf
      - ./data/nats2:/data
  nats3:
    image: nats:2.10.12-linux
    ports:
      - "4224:4222"
      - "8224:8222"
    command: [ 
        "--config", "/conf/nats.conf", 
        "--server_name", "nats3",
      ]
    depends_on:
      - 'nats1'
    networks:
      - nats
    volumes:
      - ./nats.conf:/conf/nats.conf
      - ./data/nats3:/data
networks:
  nats:
    driver: bridge